import { getStory, getFraming } from "@/lib/api";
import { ArticleCard } from "@/components/ArticleCard";
import { RegionDots } from "@/components/RegionDots";
import { TopicBadge } from "@/components/TopicBadge";
import { REGION_LABELS, REGION_TEXT_COLORS, timeAgo, formatDate } from "@/lib/utils";
import { ArrowLeft, Newspaper, Globe, Layers, Sparkles } from "lucide-react";
import Link from "next/link";
import type { Region } from "@/lib/types";

export const revalidate = 300;

export default async function StoryPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const [story, framing] = await Promise.all([
    getStory(id),
    getFraming(id),
  ]);

  if (!story) {
    return (
      <div className="max-w-5xl mx-auto px-4 py-16 text-center">
        <p className="text-lg text-muted">Story not found.</p>
      </div>
    );
  }

  const title = story.canonical_title || `Story cluster (${story.articles.length} articles)`;
  const regionKeys = Object.keys(story.articles_by_region) as Region[];

  return (
    <div className="max-w-6xl mx-auto px-4 py-8">
      <Link href="/" className="inline-flex items-center gap-1.5 text-sm text-muted hover:text-foreground mb-6 transition-colors">
        <ArrowLeft className="w-4 h-4" />
        Back to stories
      </Link>

      {/* Header */}
      <div className="mb-8">
        <div className="flex items-center gap-3 mb-3 flex-wrap">
          <TopicBadge topic={story.topic} />
          <RegionDots regions={story.regions} />
          <span className="text-xs text-muted">{timeAgo(story.first_seen)}</span>
        </div>

        <h1 className="font-serif text-2xl md:text-3xl font-bold leading-tight mb-4">
          {title}
        </h1>

        <div className="flex items-center gap-5 text-sm text-muted">
          <span className="inline-flex items-center gap-1.5">
            <Newspaper className="w-4 h-4" />
            {story.source_count} sources
          </span>
          <span className="inline-flex items-center gap-1.5">
            <Globe className="w-4 h-4" />
            {story.country_count} countries
          </span>
          <span className="inline-flex items-center gap-1.5">
            <Layers className="w-4 h-4" />
            {story.region_count} regions
          </span>
          <span>{story.articles.length} articles</span>
        </div>
      </div>

      {/* Framing Analysis */}
      {framing.framing_analysis && (
        <div className="bg-surface border border-blue-500/20 rounded-xl p-6 md:p-8 mb-8">
          <div className="flex items-center gap-2.5 mb-5">
            <Sparkles className="w-5 h-5 text-blue-400" />
            <h2 className="font-semibold text-base text-blue-400 uppercase tracking-wider">
              AI Framing Analysis
            </h2>
          </div>
          <div className="text-base md:text-lg leading-[1.8] text-foreground/90 space-y-5">
            {framing.framing_analysis.split("\n\n").filter((p: string) => !p.startsWith("## ")).map((paragraph: string, i: number) => {
              // Detect bold markdown headers like **Header**
              const parts = paragraph.split(/(\*\*[^*]+\*\*)/g);
              return (
                <p key={i}>
                  {parts.map((part: string, j: number) => {
                    if (part.startsWith("**") && part.endsWith("**")) {
                      return (
                        <strong key={j} className="font-semibold text-foreground block mb-1.5">
                          {part.slice(2, -2)}
                        </strong>
                      );
                    }
                    return <span key={j}>{part}</span>;
                  })}
                </p>
              );
            })}
          </div>
          <p className="text-sm text-muted mt-6 pt-4 border-t border-border">
            This analysis was generated by AI to highlight differences in how sources cover this story. It does not judge which framing is more correct.
          </p>
        </div>
      )}

      {/* Articles by Region */}
      <div className="space-y-8">
        {regionKeys.map((region) => {
          const articles = story.articles_by_region[region];
          return (
            <section key={region}>
              <h2 className={`flex items-center gap-2 font-semibold mb-4 ${REGION_TEXT_COLORS[region]}`}>
                <span className={`w-3 h-3 rounded-full ${
                  region === "americas" ? "bg-blue-500" :
                  region === "europe" ? "bg-emerald-500" :
                  region === "asia_pacific" ? "bg-amber-500" :
                  "bg-rose-500"
                }`} />
                {REGION_LABELS[region]}
                <span className="text-sm font-normal text-muted">({articles.length} {articles.length === 1 ? "article" : "articles"})</span>
              </h2>
              <div className="grid gap-3 md:grid-cols-2">
                {articles.map((article) => (
                  <ArticleCard key={article.id} article={article} />
                ))}
              </div>
            </section>
          );
        })}
      </div>
    </div>
  );
}
